name: Deploy Demo

on:
  push:

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install
        run: npm i

      - name: Build demo
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run build

      - name: Deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/.vuepress/dist
          single-commit: true
